### ISSUE TITLE
Remove backup counter

### ISSUE THREAD

**Issue by Sh0ham** [Foundation-Devices/passport-firmware#13]
Anytime Passport creates a backup file it names it with "passport-backup-x.7z", where x is the number of backups were created ever since Passport was initialized.

While it has no use for the user, attacker might know how many backups at least were created.

**Comment by zachherbert** [comment]
Thanks for posting @Sh0ham. I don't believe this is an issue, as it's important for Passport to create a new backup each time and not overwrite the previous backup. Maybe you deleted a multisig config, for example, and then made a backup – you'd want the old backup around in case you want to restore that config. 

@FoundationKen not sure if there is a better way to do this besides numbering the backups. Do you agree?

**Comment by FoundationKen** [comment]
As Passport does not have a clock, a user cannot rely on the timestamps of backups to know which one is newer.

The counter thus acts as a sort of clock. The `backup_num` is stored in an encrypted area of flash. In order to learn this number, the attacker would need to do one of the following:


* Have physical possession of the Passport and defeat RDP level 2 and manage to read the data that is used to form the encryption key and then read and decrypt the backup number.


* Have possession of one or more of the backup files and note it’s number.



* Login to Passport with the PIN and try to make a backup. At this point the attacker has full control of the device anyway.




Any of these situations are far more serious breeches than knowing if you have 1 backup file or 10.


Furthermore, knowing the number is say 10 doesn’t mean there are 10 microSD backup cards out there. One microSD card could have 10 backup files in the backups folder.


Let us if this addresses your concern or if there is another scenario you are considering.

—
Ken CarpenterCTO
Foundation Devices

--- original message ---
On July 18, 2021, 7:33 PM PDT ***@***.*** wrote:



Thanks for posting @Sh0ham. I don't believe this is an issue, as it's important for Passport to create a new backup each time and not overwrite the previous backup. Maybe you deleted a multisig config, for example, and then made a backup – you'd want the old backup around in case you want to restore that config.

@FoundationKen not sure if there is a better way to do this besides numbering the backups. Do you agree?

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by Sh0ham** [comment]
Thanks for commenting, @zachherbert @FoundationKen. I haven't think about different configs and I agree there should be a way to address which backup it is.
