### ISSUE TITLE
Increase "Address Verified" display time 

### ISSUE THREAD

**Issue by pmknutsen** [Foundation-Devices/passport-firmware#15]
When verifying an address the confirmation "Address Verified" is displayed for a very short time. I've found myself having to repeat the procedure twice on a couple of occasions because I glanced away while the "verified" message popped up and disappeared. My personal UI preference would be that no such confirmation auto-clears, but always has to be cleared with a key press.

**Comment by zachherbert** [comment]
Hi Per!

We agree completely! In fact this was just improved in a commit on Friday. It will be included in the next release.


It also shows you the actual address and at what index it was found.


If it didn’t find the address after searching 100 entries, it shows you which index ranges it searched, and asks if you want to continue.


Cheers!

—
Ken CarpenterCTO
Foundation Devices

--- original message ---
On July 21, 2021, 12:40 AM PDT ***@***.*** wrote:



When verifying an address the confirmation "Address Verified" is displayed for a very short time. I've found myself having to repeat the procedure twice on a couple of occasions because I glanced away while the "verified" message popped up and disappeared. My personal UI preference would be that no such confirmation auto-clears, but always has to be cleared with a key press.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---
