### ISSUE TITLE
Add QR code export function for electrum.

### ISSUE THREAD

**Issue by tuvok137** [Foundation-Devices/passport-firmware#3]
in firmware 1.0.1 there is no QR code export possible for electrum.

I had to use the BTC-pay QR code and then manually edit the string.

**Comment by zachherbert** [comment]
Thanks for reporting this issue @tuvok137. Unfortunately Electrum does not support Blockchain Commons' UR1.0 or UR2.0 standard for splitting data into multiple QR codes. 

This means that we can't sign transactions from Electrum with Passport via QR codes, because if a signed PSBT is too large then it won't fit into a single QR for Electrum to scan. So for now we've opted to only support Electrum officially via microSD card. We'll be posting an official Electrum guide in the next few days.

Hopefully Electrum can add multi QR support and we can officially support via QR codes!
