### ISSUE TITLE
Crash with errors when choosing to import a backup in SD menu

### ISSUE THREAD

**Issue by Transisto** [Foundation-Devices/passport-firmware#5]
```
  File "main.py", line 200, in run_loop
  File "uasyncio/core.py", line 87, in run_forever
  File "main.py", line 35, in main
  File "ux.py", line 63, in interact
  File "menu.py", line 286, in interact
  File "menu.py", line 279, in activate
  File "menu.py", line 68, in activate
  File "actions.py", line 966, in restore_microsd_backup
  File "actions.py", line 1038, in file_picker

OSError: [Errno 2] ENOENT
```

The SD card contain a backup.7z from a coldcard.

didn't get to make a file selection.

**Comment by zachherbert** [comment]
Thank you @Transisto. To confirm, you tried to restore a microSD backup from Coldcard?

We did not design with this use case in mind, as Passport's backup format and password is different from Coldcard's. But maybe there is some way we can enable this for advanced users. Thoughts @FoundationKen?

**Comment by FoundationKen** [comment]
The crash is fixed in the v1.0.2 firmware release.  Passport currently requires backups to be in a folder named `backups`, since this is where it saves them (keeps the clutter out of the root level).  If the `backups` folder was missing before this fix, it crashed.

The screen for entering a backup password uses a different set of words than Coldcard, though, and so even with the fix and the file in the right place you won't be able to restore the Coldcard backup today.

We could add a "Restore Coldcard Backup" menu item that uses the original word list and extracts the compatible parts of the backup file.

I'll add it for consideration to our backlog.

**Comment by Transisto** [comment]
That would be a useful feature, but still the way it's crashing right now
is awful.

The coldcard let you chose a file next the passport repeat these error in a
loop.

**Comment by zachherbert** [comment]
@FoundationKen can we close this issue since the crash is fixed – and add the ability to restore Coldcard backups to our backlog?
